server:
  port: 9090
  servlet:
    context-path: /demo
file:
  upload:
    url=static/upload/imgs

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tomorrow123456
    url: jdbc:mysql://175.27.239.242:3306/tomorrow?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
  jpa:
    hibernate:
      ddl-auto: update //自动更新
    show-sql: true  //日志中显示sql语句
